<a href="https://colab.research.google.com/github/sagasucksatlife1/QunatProjects-Main/blob/main/MachineL(Titanic).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
train= pd.read_csv("/content/train.csv")

train_2= train[["Sex","Age","Survived"]].copy()

train.shape

(891, 12)

In [98]:

train_2["Sex"]= train_2["Sex"].map({"male":0,"female":1})
train_2["Age"]= train_2["Age"].fillna(train_2["Age"].median())
train_2.head(50)

    Sex   Age  Survived
0     0  22.0         0
1     1  38.0         1
2     1  26.0         1
3     1  35.0         1
4     0  35.0         0
5     0  28.0         0
6     0  54.0         0
7     0   2.0         0
8     1  27.0         1
9     1  14.0         1
10    1   4.0         1
11    1  58.0         1
12    0  20.0         0
13    0  39.0         0
14    1  14.0         0
15    1  55.0         1
16    0   2.0         0
17    0  28.0         1
18    1  31.0         0
19    1  28.0         1
20    0  35.0         0
21    0  34.0         1
22    1  15.0         1
23    0  28.0         1
24    1   8.0         0
25    1  38.0         1
26    0  28.0         0
27    0  19.0         0
28    1  28.0         1
29    0  28.0         0
30    0  40.0         0
31    1  28.0         1
32    1  28.0         1
33    0  66.0         0
34    0  28.0         0
35    0  42.0         0
36    0  28.0         1
37    0  21.0         0
38    1  18.0         0
39    1  14.0         1
40    1  40.0         0
41    1  27.0         0
42    0  28.0         0
43    1   3.0         1
44    1  19.0         1
45    0  28.0         0
46    0  28.0         0
47    1  28.0         1
48    0  28.0         0
49    1  18.0         0

In [99]:

y= train_2[["Survived"]]
x = train_2[["Age","Sex"]]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [100]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)
y_pred= lr.predict(x_test)
y_pred

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0])

In [101]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)
print(accuracy_score(y_test,y_pred))

0.7910447761194029